import { GAME_HEIGHT, GAME_WIDTH } from "../config/config";

export default {
   background: {
      key: "register_screen_background",
      type: "sprite",
      x: 0,
      y: 0,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      anchorX: 0,
      anchorY: 0,
      visible: true,
  },
  usernameTextInputConfig:{
      x: GAME_WIDTH/2,
      y: GAME_HEIGHT/2 - 150,
      id: "login-input",
      type: "text",
      classList: "no-focus-border",
      style: {
         position: "absolute",
         background: "",
         border: "none",
         width: 300,
         height: 50,
         fontSize: 30,
      }
  },

  passwordTextInputConfig:{
   x: GAME_WIDTH/2,
   y: GAME_HEIGHT/2 - 50,
   type: "password",
   classList: "no-focus-border",
   id: "login-input",
   style: {
      position: "absolute",
      background: "",
      border: "none",
      width: 300,
      height: 50,
      fontSize: 30,
   }
  },
  nicknameTextInputConfig: {
   x: GAME_WIDTH/2,
   y: GAME_HEIGHT/2 + 50,
   type: "text",
   classList: "no-focus-border",
   id: "login-input",
   style: {
      position: "absolute",
      background: "",
      border: "none",
      width: 300,
      height: 50,
      fontSize: 30,
   }
},
  registerButtonConfig: {
   spritePush: "register_button_push",
   scaleValue: 1,
   spriteConfig: {
       key: "register_button",
       type: "sprite",
       x: GAME_WIDTH/2,
       y: GAME_HEIGHT/2 + 200,
       scaleX: 1,
       scaleY: 1,
       angle: 0,
       anchorX: 0.5,
       anchorY: 0.5,
       visible: true,
   },
},
backButtonConfig: {
    spritePush: "back_button_push",
    scaleValue: 1,
    spriteConfig: {
        key: "back_button",
        type: "sprite",
        x: 50,
        y: 150,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        anchorX: 0,
        anchorY: 1,
        visible: true,
    },
 },

 usernameText: {
    message: "Login",
    x: GAME_WIDTH/2 - 200,
    y: GAME_HEIGHT/2 - 150,
    scaleX: 1,
    scaleY: 1,
    angle: 0,
    anchorX: 1,
    anchorY: 0.5,
    visible: true,
    textConfig: {
        fontFamily: "Arial",
        fontSize: 40,
        fill: 0xffffff,
    },
 },
 passwordText: {
    message: "Password",
    x:  GAME_WIDTH/2 - 200,
    y: GAME_HEIGHT/2 - 50,
    scaleX: 1,
    scaleY: 1,
    angle: 0,
    anchorX: 1,
    anchorY: 0.5,
    visible: true,
    textConfig: {
        fontFamily: "Arial",
        fontSize: 40,
        fill: 0xffffff,
    },
 },
 nicknameText: {
    message: "Nickname",
    x:  GAME_WIDTH/2 - 200,
    y: GAME_HEIGHT/2 + 50,
    scaleX: 1,
    scaleY: 1,
    angle: 0,
    anchorX: 1,
    anchorY: 0.5,
    visible: true,
    textConfig: {
        fontFamily: "Arial",
        fontSize: 40,
        fill: 0xffffff,
    },
 }
}