import { GAME_HEIGHT } from "../../../config/config";

export const BUTTON_TYPES = ["fold", "check", "call", "raise", "bet"]
export const POKER_BAR_CONFIG = {
    bottomBar: {
        path: "",
        key: "bottom_bar",
        type: "sprite",
        x: 0,
        y: GAME_HEIGHT,
        anchorX: 0,
        anchorY: 1,
        visible: true,
    },
    moneyText: {
        message: 0,
        x: 120,
        y: 980,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        anchorX: 0,
        anchorY: 0,
        visible: true,
        textConfig: {
            fontFamily: "Arial",
            fontSize: 55,
            fill: 0xffffff,
        },
    },
    betsText: {
        message: 0,
        x: 445,
        y: 980,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        anchorX: 0,
        anchorY: 0,
        visible: true,
        textConfig: {
            fontFamily: "Arial",
            fontSize: 55,
            fill: 0xffffff,
        },
    },
    foldButton: {
        spritePush: "fold_button_push",
        scaleValue: 0.9,
        spriteConfig: {
            key: "fold_button",
            type: "sprite",
            x: 600,
            y: 1070,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            anchorX: 0,
            anchorY: 1,
            visible: true,
        },
    },
    betButton: {
        spritePush: "bet_button_push",
        scaleValue: 0.9,
        spriteConfig: {
            key: "bet_button",
            type: "sprite",
            x: 1645,
            y: 1070,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            anchorX: 0,
            anchorY: 1,
            visible: true,
        },
    },
    checkButton: {
        spritePush: "check_button_push",
        scaleValue: 0.9,
        spriteConfig: {
            key: "check_button",
            type: "sprite",
            x: 860,
            y: 1070,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            anchorX: 0,
            anchorY: 1,
            visible: true,
        },
    },
    callButton: {
        spritePush: "call_button_push",
        scaleValue: 0.9,
        spriteConfig: {
            key: "call_button",
            type: "sprite",
            x: 1120,
            y: 1070,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            anchorX: 0,
            anchorY: 1,
            visible: true,
        },
    },
    raiseButton: {
        spritePush: "raise_button_push",
        scaleValue: 0.9,
        spriteConfig: {
            key: "raise_button",
            type: "sprite",
            x: 1385,
            y: 1070,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            anchorX: 0,
            anchorY: 1,
            visible: true,
        },
    }
};
